### ISSUE TITLE
example 页代码兼容性问题

### ISSUE THREAD

**Issue by li-changyu** [realsee-developer/dnalogel#103]
目前线上[example 页](https://realsee.js.org/dnalogel/)用到了 esModule 特性，部分浏览器不支持改特性，（测试设备 iPhone xs Max，iOS 版本 12.x，打开页面白屏）是否考虑兼容到 ES5？
![image](https://user-images.githubusercontent.com/27916327/195028906-f6f3516d-fa02-49f0-8425-3272d212bde7.png)

**Comment by sansi-lcj** [comment]
开发场景不用考虑兼容低版本浏览器
