### ISSUE TITLE
parseWork 返回数据有问题  workcode是undefined

### ISSUE THREAD

**Issue by wilsoncmk** [realsee-developer/dnalogel#233]

**Comment by wilsoncmk** [comment]
通过如视vr 上传的作品 通过v1版本的entity接口拿到数据后 用parsework 解析 这个时候数据出错了， 解析后的数据workcode是undefined

**Comment by sansi-lcj** [comment]
work数据里的workcode不被解析。
parseWork报错请检查是否有改动work数据。
