### ISSUE TITLE
PanoSpatialTagPlugin 加载时机问题

### ISSUE THREAD

**Issue by li-changyu** [realsee-developer/dnalogel#46]
https://github.com/realsee-developer/dnalogel/blob/4e17d73a696bc776ba3232abbce601c1141d51d5/plugins/src/PanoSpatialTagPlugin/index.ts#L474-L484

使用 PanoSpatialTagPlugin 时发现插件依赖 modelBvhLoaded 事件，如果使用时 five 的 bvh 设置为 false 则无法正常加载。
- 目前依赖 modelBvhLoaded 事件而不是 modelLoaded 事件是出于性能考虑吗，是否可以考虑兼容 bvh 为 false 的场景？
- 如果不考虑兼容 bvh 为 false 的场景的话，能否在用户设置了bvh 为 false 同时又加载了 PanoSpatialTagPlugin 时抛出异常提醒？

**Comment by Angry-Sparrow** [comment]
好问题！
