### ISSUE TITLE
可不可以好好写个项目介绍描述下

### ISSUE THREAD

**Issue by shyandsy** [realsee-developer/dnalogel#61]
可不可以好好写个项目介绍描述下

**Comment by Angry-Sparrow** [comment]
首页readme为仓库介绍：https://github.com/realsee-developer/dnalogel

插件readme在plugins目录下：https://github.com/realsee-developer/dnalogel/tree/main/plugins


其他文档会陆续完善补充。

感谢意见！

**Comment by shyandsy** [comment]
readme

项目背景，为啥有这个东西，这是干啥的。贴点截图，效果

上来就“插件开发”，心疼你啊
